### ISSUE TITLE
clang linker error 

### ISSUE THREAD

**Issue by lcjensen** [TadasBaltrusaitis/OpenFace#175]
I am attempting to compile on ubuntu 16.10. I have been having some of the same problems (I suspect) as #44 and #146 report. I've downgraded clang, g++ and c++ as #146 suggests. I am now left with one error (at 92%) that I cannot resolve, hoping someone could point me in the right direction. 

This is my cmake: 
` cmake -D CMAKE_CXX_COMPILER=clang++-3.7 -D CMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -I/usr/include/libcxxabi" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11 -stdlib=libc++ -lc++abi" -D CMAKE_BUILD_TYPE=RELEASE ..`

which gives me this error:
`/usr/bin/ld: /usr/local/lib/libopencv_core.a(ocl.cpp.o): undefined reference to symbol '_ZNSo9_M_insertIdEERSoT_@@GLIBCXX_3.4.9'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/build.make:142: recipe for target 'bin/FaceLandmarkImg' failed
make[2]: *** [bin/FaceLandmarkImg] Error 1
CMakeFiles/Makefile2:252: recipe for target 'exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all' failed
make[1]: *** [exe/FaceLandmarkImg/CMakeFiles/FaceLandmarkImg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

Any ideas of what I'm doing wrong?

**Comment by maamountki** [comment]
You miss linking to a library maybe it's math, Try add -lm flag.

**Comment by lcjensen** [comment]
@maamountki thanks for the suggestion, but adding the flag had no effect.

**Comment by chiragraman** [comment]
From a cursory examination of the error message, it seems like the code is being compiled against libstdc++ instead of libc++ as specified in your cmake command. I'll look into this shortly and hopefully have a more specific suggestion, but that might be one thing to inspect in more detail.

**Comment by lcjensen** [comment]
thanks for the suggestion @chiragraman. I instead attempted a windows installation which was far more simple. It works like a charm :)

**Comment by sunguwei** [comment]
I have the same problem, can anyone provide the suggestion? Thanks very much.

**Comment by sunguwei** [comment]
I have the same problem, can anyone provide the suggestion? Thanks very much.

**Comment by sunguwei** [comment]
I have the same problem, can anyone provide the suggestion? Thanks very much.

**Comment by TadasBaltrusaitis** [comment]
This should be fixed now.
