### ISSUE TITLE
Link error on windows because of sgemm_

### ISSUE THREAD

**Issue by wolfviking0** [TadasBaltrusaitis/OpenFace#635]
**Describe the bug**
I have some issue when I try to link my executable with openface. It’s complaining about sgemm_.
I am using the latest version of openblas from xianyi. The openblas static library it’s used on many other project as caffe2 / tensorflow / ... on windows.

Any idea why openface will not build fine on windows with openblas.

Thanks

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version openblas 0.3.5, openface 2.1.0
 - Compiler cl.exe using cmake 

**Additional context**
Exact log error : 
LandmarkDetector.lib(CEN_patch_expert.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(LandmarkDetectorModel.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(PDM.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(CNN_utils.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(CCNF_patch_expert.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
bin\openfaceengine.dll : fatal error LNK1120: 1 unresolved externals

**Comment by wolfviking0** [comment]
It seems on windows the OpenBlas function sgemm do not have underscore.
I just change the header stdafx.h in order to support that : 

    /*Set the number of threads on runtime.*/
    void openblas_set_num_threads(int num_threads);

    #ifdef OPENBLAS_NEEDBUNDERSCORE
            void sgemm_(char *, char *, blasint *, blasint *, blasint *, float *,
		float  *, blasint *, float  *, blasint *, float  *, float  *, blasint *);
    #else
            void sgemm(char *, char *, blasint *, blasint *, blasint *, float *,
    		float  *, blasint *, float  *, blasint *, float  *, float  *, blasint *);

        #define sgemm_ sgemm

    #endif

**Comment by TadasBaltrusaitis** [comment]
Will make sure to include this in the new version, as I was working with OpenBLAS 0.3.3 this issue did not come up
