### PR TITLE
Update the OpenCV constants to the corresponding ones in cpp namespace.

### PR DESCRIPTION
**Pull request by taoyudong**
Change some macros to enable OpenFace with OpenCV3.4 (Not using #ifdef so the updated version can only work with OpenCV3.4. Can be done in the future)

### CODE REVIEW

**Comment by taoyudong** [comment]
Tested on my mac high Sierra 10.13.6 and should be deployable for other OS. OpenCV version is 3.4.2 from homebrew. Have not been heavily tested.
I do not have time to provide a version compatible with both versions in the coming weeks. If desired, I might be able to finish it in Oct. It should be easy with #ifdef.

**Comment by TadasBaltrusaitis** [comment]
Hi, I'm a bit confused by the PR.

OpenFace already works with OpenCV 3.4, or did you encounter any issues with that?

**Comment by taoyudong** [comment]
The title is kind of misleading here. It is not really due to the version of OpenCV.
The constant used in OpenFace, such as CV_BGR2GRAY. They are defined in opencv2/imgproc/type_c.h, which is designed for c interface.
When I specify to use cpp compiler in mac, these headers will not be loaded and thus produce "use of undeclared identifier ***" error.
This can surely be resolved by using the proper compiler setting. However, it would be better to use the equivalent constant defined in the namespace for cpp project.

**Comment by TadasBaltrusaitis** [comment]
Sounds good, thanks for the explanation. Before completing the pull request could you make it to develop rather that the master branch? I use develop as a stop-gap before including changes into master.

**Comment by taoyudong** [comment]
Done

**Comment by TadasBaltrusaitis** [comment]
Thanks!
